### ISSUE TITLE
New Auto: move the robot for 2 seconds forward

### ISSUE THREAD

**Issue by IamIisI** [Auth-Xero/9430-WestCoastDriveBot#2]
**Idea**
We want to begin having the robot move itself.

**Goal**
The robot should be able to move itself forward for 2 seconds on command.

**Purpose**
This will allow innovations later, allowing it to follow a path.

**Comment by bbontrager89** [comment]
We need to be more specific for the conditions of "success" when making issues. 
Good job on being clear with the intent, that the robot needs to be autonomous, mobile, and have a starting and stopping point.
1. The starting point will implicitly be where the robot is placed (autonomous will always start after the robot is placed and before teleop
2. Where should the endpoint be? Determined by distance? Time? Should the robot be turning, or should the robot move in a straight line (ie. is there a defined trajectory?)

Please edit this issue with the specifics and then, once you're complete, feel free to remove the "question" label. This issue will be closed as wontfix if this is not resolved.

**Comment by salut-hi** [comment]
We've decided to close the issue because now we're switching over to using pathplanner for auto. Pathplanner also works by constructing a path from one point to another instead of using time and distance.
